/* -LICENSE-START-
** Copyright (c) 2019 Blackmagic Design
**  
** Permission is hereby granted, free of charge, to any person or organization 
** obtaining a copy of the software and accompanying documentation (the 
** "Software") to use, reproduce, display, distribute, sub-license, execute, 
** and transmit the Software, and to prepare derivative works of the Software, 
** and to permit third-parties to whom the Software is furnished to do so, in 
** accordance with:
** 
** (1) if the Software is obtained from Blackmagic Design, the End User License 
** Agreement for the Software Development Kit ("EULA") available at 
** https://www.blackmagicdesign.com/EULA/DeckLinkSDK; or
** 
** (2) if the Software is obtained from any third party, such licensing terms 
** as notified by that third party,
** 
** and all subject to the following:
** 
** (3) the copyright notices in the Software and this entire statement, 
** including the above license grant, this restriction and the following 
** disclaimer, must be included in all copies of the Software, in whole or in 
** part, and all derivative works of the Software, unless such copies or 
** derivative works are solely in the form of machine-executable object code 
** generated by a source language processor.
** 
** (4) THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT 
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
** DEALINGS IN THE SOFTWARE.
** 
** A copy of the Software is available free of charge at 
** https://www.blackmagicdesign.com/desktopvideo_sdk under the EULA.
** 
** -LICENSE-END-
*/

#include <QCoreApplication>
#include <QMessageBox>
#include <QTextStream>

#include "com_ptr.h"
#include "DeckLinkInputDevice.h"
#include <QDebug>
#include "diag/DiagProbe.h"

DeckLinkInputDevice::DeckLinkInputDevice(QObject* owner, com_ptr<IDeckLink>& device) : 
	m_owner(owner),
	m_refCount(1),
	m_deckLink(device),
	m_deckLinkInput(IID_IDeckLinkInput, device),
	m_deckLinkConfig(IID_IDeckLinkConfiguration, device),
	m_deckLinkHDMIInputEDID(IID_IDeckLinkHDMIInputEDID, device),
	m_deckLinkStatus(IID_IDeckLinkStatus, device),
	m_supportsFormatDetection(false),
	m_currentlyCapturing(false),
	m_applyDetectedInputMode(false),
	m_supportedInputConnections(0)
{
	// m_deckLink(device) already holds a reference; an extra AddRef() here was never released
}

HRESULT	DeckLinkInputDevice::QueryInterface(REFIID iid, LPVOID *ppv)
{
	CFUUIDBytes		iunknown;
	HRESULT			result = E_NOINTERFACE;

	if (ppv == nullptr)
		return E_INVALIDARG;

	// Initialise the return result
	*ppv = nullptr;

	// Obtain the IUnknown interface and compare it the provided REFIID
	iunknown = CFUUIDGetUUIDBytes(IUnknownUUID);
	if (memcmp(&iid, &iunknown, sizeof(REFIID)) == 0)
	{
		*ppv = this;
		AddRef();
		result = S_OK;
	}
	else if (memcmp(&iid, &IID_IDeckLinkInputCallback, sizeof(REFIID)) == 0)
	{
		*ppv = (IDeckLinkInputCallback*)this;
		AddRef();
		result = S_OK;
	}

	return result;
}

ULONG DeckLinkInputDevice::AddRef(void)
{
	return ++m_refCount;
}

ULONG DeckLinkInputDevice::Release(void)
{
	ULONG newRefValue = --m_refCount;
	if (newRefValue == 0)
		delete this;

	return newRefValue;
}

bool DeckLinkInputDevice::Init()
{
	com_ptr<IDeckLinkProfileAttributes>		deckLinkAttributes(IID_IDeckLinkProfileAttributes, m_deckLink);
	const char*								deviceNameStr;

	if (!m_deckLinkInput)
	{
		// This may occur if device does not have input interface, for instance DeckLink Mini Monitor.
		return false;
	}
		
	// The configuration interface is valid until destructor to retain input connector setting
	if (!m_deckLinkConfig)
	{
		QMessageBox::critical(qobject_cast<QWidget*>(m_owner), "DeckLink Input initialization error", "Unable to query IDeckLinkConfiguration object interface");
		return false;
	}

	if (!deckLinkAttributes)
	{
		QMessageBox::critical(qobject_cast<QWidget*>(m_owner), "DeckLink Input initialization error", "Unable to query IDeckLinkProfileAttributes object interface");
		return false;
	}

	// Check if input mode detection is supported.
	if (deckLinkAttributes->GetFlag(BMDDeckLinkSupportsInputFormatDetection, &m_supportsFormatDetection) != S_OK)
		m_supportsFormatDetection = false;

	// Get the supported input connections for the device
	if (deckLinkAttributes->GetInt(BMDDeckLinkVideoInputConnections, &m_supportedInputConnections) != S_OK)
		m_supportedInputConnections = 0;
		
	// Enable all EDID functionality if possible
	if (m_deckLinkHDMIInputEDID)
	{
		int64_t allKnownRanges = bmdDynamicRangeSDR | bmdDynamicRangeHDRStaticPQ | bmdDynamicRangeHDRStaticHLG;
		m_deckLinkHDMIInputEDID->SetInt(bmdDeckLinkHDMIInputEDIDDynamicRange, allKnownRanges);
		m_deckLinkHDMIInputEDID->WriteToEDID();
	}

	// Get device name
	if (m_deckLink->GetDisplayName(&deviceNameStr) == S_OK)
	{
		m_deviceName = deviceNameStr;
		free((void*)deviceNameStr);
	}
	else
	{
		m_deviceName = "DeckLink";
	}

	return true;
}

void DeckLinkInputDevice::queryDisplayModes(DisplayModeQueryFunc func)
{
	com_ptr<IDeckLinkDisplayModeIterator>	displayModeIterator;
	com_ptr<IDeckLinkDisplayMode>			displayMode;

	if (m_deckLinkInput->GetDisplayModeIterator(displayModeIterator.releaseAndGetAddressOf()) != S_OK)
		return;

	while (displayModeIterator->Next(displayMode.releaseAndGetAddressOf()) == S_OK)
	{
		func(displayMode);
	}
}

bool DeckLinkInputDevice::startCapture(BMDDisplayMode displayMode, IDeckLinkScreenPreviewCallback* screenPreviewCallback, bool applyDetectedInputMode)
{
	HRESULT				result;
	BMDVideoInputFlags	videoInputFlags = bmdVideoInputFlagDefault;

	m_applyDetectedInputMode = applyDetectedInputMode;

	// Enable input video mode detection if the device supports it
	if (m_supportsFormatDetection)
		videoInputFlags |=  bmdVideoInputEnableFormatDetection;

	// Set the screen preview
	m_deckLinkInput->SetScreenPreviewCallback(screenPreviewCallback);

	// Set capture callback
	m_deckLinkInput->SetCallback(this);

	// Set the video input mode
	result = m_deckLinkInput->EnableVideoInput(displayMode, bmdFormat8BitYUV, videoInputFlags);
	m_currentDisplayMode = displayMode;
	m_currentPixelFormat = bmdFormat8BitYUV;
	if (result != S_OK)
	{
		QMessageBox::critical(qobject_cast<QWidget*>(m_owner), "Error starting the capture", "This application was unable to select the chosen video mode. Perhaps, the selected device is currently in-use.");
		return false;
	}

	// Report the first signal state after (re)starting
	m_lastSignalValid = -1;

	// Start the capture
	result = m_deckLinkInput->StartStreams();
	if (result != S_OK)
	{
		QMessageBox::critical(qobject_cast<QWidget*>(m_owner), "Error starting the capture", "This application was unable to start the capture. Perhaps, the selected device is currently in-use.");
		return false;
	}

	m_currentlyCapturing = true;

	return true;
}

void DeckLinkInputDevice::stopCapture()
{
	if (m_deckLinkInput)
	{
		// Stop the capture
		m_deckLinkInput->StopStreams();

		// Unregister the screen preview callback
		m_deckLinkInput->SetScreenPreviewCallback(nullptr);

		// Unregister the input callback
		m_deckLinkInput->SetCallback(nullptr);

		// Disable video input
		m_deckLinkInput->DisableVideoInput();
	}

	m_currentlyCapturing = false;
}

// Usable PCIe bandwidth of this card's link, in MB/s (0 if it cannot be read).
// ~80% of the raw rate after protocol overhead: Gen1 250, Gen2 500, Gen3 985 MB/s per lane.
double DeckLinkInputDevice::pcieLinkCapacityMBps()
{
	if (!m_deckLinkStatus)
		return 0.0;
	int64_t width = 0, gen = 0;
	if (m_deckLinkStatus->GetInt(bmdDeckLinkStatusPCIExpressLinkWidth, &width) != S_OK ||
	    m_deckLinkStatus->GetInt(bmdDeckLinkStatusPCIExpressLinkSpeed, &gen) != S_OK || width <= 0 || gen <= 0)
		return 0.0;

	const double perLane = (gen >= 3) ? 985.0 : (gen == 2) ? 500.0 : 250.0;
	return width * perLane * 0.8;
}

HRESULT DeckLinkInputDevice::VideoInputFormatChanged (BMDVideoInputFormatChangedEvents notificationEvents, IDeckLinkDisplayMode *newMode, BMDDetectedVideoInputFormatFlags detectedSignalFlags)
{
	HRESULT 		result;
	BMDPixelFormat	pixelFormat;

	// Unexpected callback when auto-detect mode not enabled
	if (!m_applyDetectedInputMode)
		return E_FAIL;

	// Capture in the source's colour model at 8 bits (the smallest format per colour model):
	//  - YCbCr 4:2:2 -> 8-bit YUV, 2 bytes/pixel
	//  - RGB 4:4:4   -> 8-bit ARGB, 4 bytes/pixel. The Mini Recorder 4K does not convert an RGB
	//    input to YUV (it delivers only "no input" frames), so RGB must be captured as RGB.
	// Both formats are supported by the recorder.
	if (detectedSignalFlags & bmdDetectedVideoInputRGB444)
		pixelFormat = bmdFormat8BitARGB;
	else if (detectedSignalFlags & bmdDetectedVideoInputYCbCr422)
		pixelFormat = bmdFormat8BitYUV;
	else
		// Unexpected detected video input format flags
		return E_INVALIDARG;

	// Restart only if the display mode or the pixel format we capture in actually changes.
	// Restarting on every colorspace notification looped endlessly (the card keeps reporting the
	// difference between the source and the capture format) and delivered no picture.
	const BMDDisplayMode displayMode = newMode->GetDisplayMode();
	if (displayMode == m_currentDisplayMode && pixelFormat == m_currentPixelFormat)
		return S_OK;

	BMDTimeValue frameDuration = 0;
	BMDTimeScale timeScale = 0;
	newMode->GetFrameRate(&frameDuration, &timeScale);
	const double fps = frameDuration ? double(timeScale) / frameDuration : 0.0;
	qInfo().nospace() << "DeckLink input detected: " << newMode->GetWidth() << "x" << newMode->GetHeight()
	                  << " @ " << fps << " fps, "
	                  << ((detectedSignalFlags & bmdDetectedVideoInputRGB444) ? "RGB 4:4:4" : "YCbCr 4:2:2")
	                  << ((detectedSignalFlags & bmdDetectedVideoInput10BitDepth) ? " 10-bit" :
	                      (detectedSignalFlags & bmdDetectedVideoInput12BitDepth) ? " 12-bit" : " 8-bit")
	                  << "; capturing as " << (pixelFormat == bmdFormat8BitARGB ? "8-bit ARGB" : "8-bit YUV");

	// Warn if the input needs more than the card's PCIe link can carry: the card then delivers
	// only part of the frames, and the picture stutters or lags behind.
	const double bytesPerPixel = (pixelFormat == bmdFormat8BitARGB) ? 4.0 : 2.0;
	const double megabytesPerSecond = double(newMode->GetWidth()) * newMode->GetHeight() * bytesPerPixel * fps / 1e6;
	const double linkMegabytesPerSecond = pcieLinkCapacityMBps();
	if (linkMegabytesPerSecond > 0.0 && megabytesPerSecond > linkMegabytesPerSecond * 0.95)
		qWarning().nospace() << "DeckLink: input needs " << int(megabytesPerSecond) << " MB/s but the card's PCIe link carries about "
		                     << int(linkMegabytesPerSecond) << " MB/s: expect about " << int(fps * linkMegabytesPerSecond / megabytesPerSecond)
		                     << " of " << int(fps) << " frames per second. Use a lighter input format "
		                     << "(lower resolution/frame rate, or YCbCr instead of RGB).";

	// Stop the capture
	m_deckLinkInput->StopStreams();

	result = m_deckLinkInput->EnableVideoInput(displayMode, pixelFormat, bmdVideoInputEnableFormatDetection);
	if (result != S_OK)
	{
		// Called on the DeckLink thread: no widgets here
		qCritical() << "DeckLink: unable to set the detected input mode";
		return result;
	}
	m_currentDisplayMode = displayMode;
	m_currentPixelFormat = pixelFormat;

	// Start the capture
	result = m_deckLinkInput->StartStreams();
	if (result != S_OK)
	{
		qCritical() << "DeckLink: unable to restart capture after an input format change";
		return result;
	}

	// Notify UI of the new display mode (also when only the colour space changed, so the
	// on-screen label always matches what is really being captured)
	if (m_owner != nullptr)
		QCoreApplication::postEvent(m_owner, new DeckLinkInputFormatChangedEvent(displayMode, newMode->GetWidth(), newMode->GetHeight(), fps));

	return S_OK;
}

HRESULT DeckLinkInputDevice::VideoInputFrameArrived(IDeckLinkVideoInputFrame* videoFrame, IDeckLinkAudioInputPacket* /* audioPacket */)
{
    if (videoFrame == nullptr)
        return S_OK;

    DIAG_INPUT_FRAME();
    bool signalValid = (videoFrame->GetFlags() & bmdFrameHasNoInputSource) == 0;

    // Only notify the GUI when the signal state changes; posting an event for every frame
    // added avoidable load to the GUI thread's event queue.
    if (m_owner != nullptr && m_lastSignalValid.exchange(signalValid ? 1 : 0) != (signalValid ? 1 : 0))
    {
        auto* event = new DeckLinkInputFrameArrivedEvent(signalValid);
        QCoreApplication::postEvent(m_owner, event);
    }

    // Hand the frame to the recorder directly from the capture thread (no GUI involvement)
    if (IVideoFrameSink* sink = m_frameSink.load())
        sink->onVideoFrame(videoFrame);

    return S_OK;
}



DeckLinkInputFormatChangedEvent::DeckLinkInputFormatChangedEvent(BMDDisplayMode displayMode, long width, long height, double fps)
	: QEvent(kVideoFormatChangedEvent), m_displayMode(displayMode), m_width(width), m_height(height), m_fps(fps)
{
}


DeckLinkInputFrameArrivedEvent::DeckLinkInputFrameArrivedEvent(bool signalValid)
    : QEvent(static_cast<QEvent::Type>(kVideoFrameArrivedEvent)),
      m_signalValid(signalValid)
{
}

bool DeckLinkInputFrameArrivedEvent::SignalValid() const
{
    return m_signalValid;
}
