/* -LICENSE-START-
** Copyright (c) 2019 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation (the
** "Software") to use, reproduce, display, distribute, sub-license, execute,
** and transmit the Software, and to prepare derivative works of the Software,
** and to permit third-parties to whom the Software is furnished to do so, in
** accordance with:
**
** (1) if the Software is obtained from Blackmagic Design, the End User License
** Agreement for the Software Development Kit ("EULA") available at
** https://www.blackmagicdesign.com/EULA/DeckLinkSDK; or
**
** (2) if the Software is obtained from any third party, such licensing terms
** as notified by that third party,
**
** and all subject to the following:
**
** (3) the copyright notices in the Software and this entire statement,
** including the above license grant, this restriction and the following
** disclaimer, must be included in all copies of the Software, in whole or in
** part, and all derivative works of the Software, unless such copies or
** derivative works are solely in the form of machine-executable object code
** generated by a source language processor.
**
** (4) THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
**
** A copy of the Software is available free of charge at
** https://www.blackmagicdesign.com/desktopvideo_sdk under the EULA.
**
** -LICENSE-END-
*/

#include "DeckLinkOpenGLWidget.h"
#include <QOpenGLFunctions>
#include <QDebug>
#include <QPainter>
#include <QMatrix4x4>
#include <QOpenGLExtraFunctions>
#include <QtConcurrent/QtConcurrent>
#include <QFutureWatcher>
#include "diag/DiagProbe.h"

///
/// DeckLinkOpenGLDelegate
///

DeckLinkOpenGLDelegate::DeckLinkOpenGLDelegate() : m_refCount(1)
{
}

/// IUnknown methods

HRESULT DeckLinkOpenGLDelegate::QueryInterface(REFIID iid, LPVOID *ppv)
{
    CFUUIDBytes iunknown;
    HRESULT result = S_OK;

    if (ppv == nullptr)
        return E_INVALIDARG;

    // Obtain the IUnknown interface and compare it the provided REFIID
    iunknown = CFUUIDGetUUIDBytes(IUnknownUUID);
    if (memcmp(&iid, &iunknown, sizeof(REFIID)) == 0)
    {
        *ppv = this;
        AddRef();
    }
    else if (memcmp(&iid, &IID_IDeckLinkScreenPreviewCallback, sizeof(REFIID)) == 0)
    {
        *ppv = static_cast<IDeckLinkScreenPreviewCallback *>(this);
        AddRef();
    }
    else
    {
        *ppv = nullptr;
        result = E_NOINTERFACE;
    }

    return result;
}

ULONG DeckLinkOpenGLDelegate::AddRef()
{
    return ++m_refCount;
}

ULONG DeckLinkOpenGLDelegate::Release()
{
    ULONG newRefValue = --m_refCount;
    if (newRefValue == 0)
        delete this;

    return newRefValue;
}

/// IDeckLinkScreenPreviewCallback methods

// HRESULT DeckLinkOpenGLDelegate::DrawFrame(IDeckLinkVideoFrame* frame)
// {
// 	emit frameArrived(com_ptr<IDeckLinkVideoFrame>(frame));
// 	return S_OK;
// }

HRESULT DeckLinkOpenGLDelegate::DrawFrame(IDeckLinkVideoFrame *frame)
{
    // Called on the DeckLink thread. Replace the pending frame instead of queueing every frame:
    // queued copies are never dropped, so a GUI thread that falls behind would show ever older video.
    {
        std::lock_guard<std::mutex> lock(m_frameMutex);
        m_latestFrame = com_ptr<IDeckLinkVideoFrame>(frame);
    }

    const bool schedule = !m_deliveryPending.exchange(true);
    DIAG_FRAME_EMITTED(frame, schedule ? 1 : 0);
    if (schedule)
        QMetaObject::invokeMethod(this, [this]() { deliverLatestFrame(); }, Qt::QueuedConnection);

    return S_OK;
}

void DeckLinkOpenGLDelegate::deliverLatestFrame()
{
    // Clear the flag before taking the frame so a frame arriving meanwhile schedules a new delivery
    m_deliveryPending = false;

    com_ptr<IDeckLinkVideoFrame> frame;
    {
        std::lock_guard<std::mutex> lock(m_frameMutex);
        frame = m_latestFrame;
    }

    DIAG_FRAME_RECEIVED(frame.get());
    emit frameArrived(frame);
}

// HRESULT DeckLinkOpenGLDelegate::DrawFrame(IDeckLinkVideoFrame* frame)
// {
//     auto framePtr = com_ptr<IDeckLinkVideoFrame>(frame);
//     emit frameArrived(framePtr);             // For OpenGL rendering
//     emit frameForRecording(framePtr);        // For recording pipeline
//     return S_OK;
// }

///
/// DeckLinkOpenGLWidget
///

DeckLinkOpenGLWidget::DeckLinkOpenGLWidget(QWidget *parent) : QOpenGLWidget(parent)
{
    m_deckLinkScreenPreviewHelper = CreateOpenGL3ScreenPreviewHelper();
    m_delegate = make_com_ptr<DeckLinkOpenGLDelegate>();

    // The delegate already hands frames over to the GUI thread (latest frame only)
    connect(m_delegate.get(), &DeckLinkOpenGLDelegate::frameArrived, this, &DeckLinkOpenGLWidget::setFrame);
}

DeckLinkOpenGLWidget::~DeckLinkOpenGLWidget()
{
    releaseGLResources();
}

void DeckLinkOpenGLWidget::clear()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    if (m_delegate)
        m_delegate->DrawFrame(nullptr);
}

/// QOpenGLWidget methods

void DeckLinkOpenGLWidget::initializeGL()
{
    // Called again with a NEW context whenever the widget is reparented, e.g. the dashboard's
    // fullscreen toggle moves it into a separate window. GL objects belong to the context that
    // created them, so they are rebuilt here and released before the old context goes away.
    // qDebug() << "initialize GL";
    if (m_deckLinkScreenPreviewHelper)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        m_deckLinkScreenPreviewHelper->InitializeGL();
    }

    if (!m_blitter.isCreated() && !m_blitter.create())
        qWarning() << "[DeckLinkOpenGLWidget] Could not create texture blitter; flip is disabled";

    // Free them while their own context is still alive (deleting GL objects under a different
    // context crashes). UniqueConnection: initializeGL() runs again for every new context.
    connect(context(), &QOpenGLContext::aboutToBeDestroyed,
            this, &DeckLinkOpenGLWidget::releaseGLResources, Qt::UniqueConnection);
}

void DeckLinkOpenGLWidget::releaseGLResources()
{
    makeCurrent();
    m_flipFbo.reset();
    if (m_blitter.isCreated())
        m_blitter.destroy();
    doneCurrent();
}

// void DeckLinkOpenGLWidget::paintGL()
// {
// 	// qDebug() << "Paint GL";
// 	std::lock_guard<std::mutex> lock(m_mutex);
// 	m_deckLinkScreenPreviewHelper->PaintGL();
// }

// void DeckLinkOpenGLWidget::paintGL()
// {
//     std::lock_guard<std::mutex> lock(m_mutex);

//     if (!m_deckLinkScreenPreviewHelper)
//         return;

//     // Step 1: Draw raw video frame to OpenGL buffer
//     m_deckLinkScreenPreviewHelper->PaintGL();

//     // Step 2: Grab current frame
//     QImage frame = grabFramebuffer();

//     // Step 3: Apply flip based on m_flipStep
//     QImage flippedFrame;
//     switch (m_flipStep)
//     {
//         case 0:
//             flippedFrame = frame;
//             break;
//         case 1:
//             flippedFrame = frame.mirrored(true, false);  // horizontal
//             break;
//         case 2:
//             flippedFrame = frame.mirrored(true, true);   // horizontal + vertical
//             break;
//         case 3:
//             flippedFrame = frame.mirrored(false, true);  // vertical (of step 2)
//             break;
//         default:
//             flippedFrame = frame;
//             break;
//     }

//     // Step 4: Draw flipped image
//     QPainter painter(this);
//     painter.setRenderHint(QPainter::SmoothPixmapTransform);
//     painter.drawImage(0, 0, flippedFrame);

//     // Step 5: Overlay text
//     painter.setPen(Qt::white);
//     painter.setFont(QFont("Arial", 24, QFont::Bold));
//     painter.drawText(20, 40, QStringLiteral("🔴 Live • 3840×2160"));

//     painter.end();
// }

void DeckLinkOpenGLWidget::setInputSource(const QString &source)
{
    // qDebug() << "[setInputSource] this=" << this << ", source=" << source;
    m_inputSource = source;
    update();
}

void DeckLinkOpenGLWidget::paintGL()
{
    // qDebug() << "[paintGL] this=" << this << ", m_inputSource=" << m_inputSource;
    DIAG_SCOPE_PAINT();

    std::lock_guard<std::mutex> lock(m_mutex);

    if (!m_deckLinkScreenPreviewHelper)
        return;

    // Flip entirely on the GPU. Reading the framebuffer back and mirroring it on the CPU every
    // frame stalled the GUI thread and let the live view fall behind the camera.
    const bool flipH = (m_flipStep == 1 || m_flipStep == 2);
    const bool flipV = (m_flipStep == 2 || m_flipStep == 3);

    if ((flipH || flipV) && m_blitter.isCreated())
    {
        QOpenGLExtraFunctions *f = context()->extraFunctions();
        const QSize fbSize = size() * devicePixelRatioF();

        if (!m_flipFbo || m_flipFbo->size() != fbSize)
            m_flipFbo = std::make_unique<QOpenGLFramebufferObject>(fbSize);

        // Step 1: Draw raw video frame into the offscreen buffer
        m_flipFbo->bind();
        f->glViewport(0, 0, fbSize.width(), fbSize.height());
        f->glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
        f->glClear(GL_COLOR_BUFFER_BIT);
        m_deckLinkScreenPreviewHelper->PaintGL();

        // Step 2: Draw it mirrored into the widget
        f->glBindFramebuffer(GL_FRAMEBUFFER, defaultFramebufferObject());
        f->glViewport(0, 0, fbSize.width(), fbSize.height());
        QMatrix4x4 target;
        target.scale(flipH ? -1.0f : 1.0f, flipV ? -1.0f : 1.0f);
        m_blitter.bind();
        m_blitter.blit(m_flipFbo->texture(), target, QOpenGLTextureBlitter::OriginBottomLeft);
        m_blitter.release();
    }
    else
    {
        // Draw raw video frame straight into the widget
        m_deckLinkScreenPreviewHelper->PaintGL();
    }

    // Step 3: Overlay. Without a valid input the last frame stays on screen and would look
    // live, so the picture is covered and the loss is stated plainly.
    if (!m_signalValid)
    {
        QPainter painter(this);
        painter.fillRect(rect(), QColor(0, 0, 0, 200));
        painter.setPen(QColor(255, 64, 64));
        painter.setFont(QFont("Arial", 36, QFont::Bold));
        painter.drawText(rect(), Qt::AlignCenter, tr("NO SIGNAL\nCheck the camera and cable"));
    }
    else if (m_showLabel)
    {
        QPainter painter(this);
        painter.setPen(Qt::white);
        painter.setFont(QFont("Arial", 24, QFont::Bold));
        // Real detected format, not a fixed string
        painter.drawText(20, 40, QStringLiteral("🔴 Live • %1%2")
                                     .arg(m_inputSource.isEmpty() ? QString() : m_inputSource + " ")
                                     .arg(m_modeText.isEmpty() ? tr("detecting…") : m_modeText));
    }
}

void DeckLinkOpenGLWidget::resizeGL(int width, int height)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    QOpenGLFunctions *f = context()->functions();
    f->glViewport(0, 0, width, height);
}

/// DeckLinkOpenGLWidget slots

// void DeckLinkOpenGLWidget::setFrame(com_ptr<IDeckLinkVideoFrame> frame)
// {
// 	// qDebug() << "setFrame GL" << frame.get();
// 	if (m_deckLinkScreenPreviewHelper)
// 	{
// 		m_deckLinkScreenPreviewHelper->SetFrame(frame.get());
// 		update();
// 	}
// }

void DeckLinkOpenGLWidget::setFrame(com_ptr<IDeckLinkVideoFrame> frame)
{
    if (!frame)
    {
        qDebug() << "[DeckLinkOpenGLWidget] Received null frame!";
        return;
    }

    // qDebug() << "[DeckLinkOpenGLWidget] Received frame:" << frame.get();

    if (m_deckLinkScreenPreviewHelper)
    {
        m_deckLinkScreenPreviewHelper->SetFrame(frame.get());
        update();
    }
}

void DeckLinkOpenGLWidget::setSharedDelegate(const com_ptr<DeckLinkOpenGLDelegate> &delegate)
{
    std::lock_guard<std::mutex> lock(m_mutex);

    if (!delegate)
        return;

    // Disconnect old delegate if it existed
    if (m_delegate)
        disconnect(m_delegate.get(), nullptr, this, nullptr);

    m_delegate = delegate;

    connect(m_delegate.get(), &DeckLinkOpenGLDelegate::frameArrived, this, &DeckLinkOpenGLWidget::setFrame);
}

com_ptr<DeckLinkOpenGLDelegate> DeckLinkOpenGLWidget::delegate()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    return m_delegate;
}

void DeckLinkOpenGLWidget::setFlipStep(int step)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_flipStep = step % 5;
    update();
}

// bool DeckLinkOpenGLWidget::saveSnapshot(const QString& path)
// {
//     QImage snapshot = grabFramebuffer();  // Grabs the current OpenGL frame
//     if (snapshot.isNull())
//         return false;

//     return snapshot.save(path);  // Automatically infers format from extension
// }

bool DeckLinkOpenGLWidget::saveSnapshot(const QString &path, std::function<void(bool ok)> onSaved)
{
    QImage snapshot = grabFramebuffer();

    if (snapshot.isNull())
    {
        // qDebug() << "❌ Snapshot is null.";
        return false;
    }

    // Encode and write off the GUI thread; report the real outcome afterwards
    auto *watcher = new QFutureWatcher<bool>(this);
    connect(watcher, &QFutureWatcher<bool>::finished, this, [watcher, path, onSaved]() {
        const bool success = watcher->result();
        watcher->deleteLater();
        qDebug() << (success ? "✅ Snapshot saved:" : "❌ Save failed:") << path;
        if (onSaved)
            onSaved(success);
    });
    watcher->setFuture(QtConcurrent::run([snapshot, path]() {
        return snapshot.save(path, nullptr, 95); // format from the extension (.jpg / .png)
    }));

    return true;
}

void DeckLinkOpenGLWidget::setSignalValid(bool valid)
{
    if (m_signalValid == valid)
        return;
    m_signalValid = valid;
    update();
}

void DeckLinkOpenGLWidget::setModeText(const QString &modeText)
{
    if (m_modeText == modeText)
        return;
    m_modeText = modeText;
    update();
}

void DeckLinkOpenGLWidget::setShowLabel(bool show)
{
    m_showLabel = show;
    update();
}