/* -LICENSE-START-
** Copyright (c) 2019 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation (the
** "Software") to use, reproduce, display, distribute, sub-license, execute,
** and transmit the Software, and to prepare derivative works of the Software,
** and to permit third-parties to whom the Software is furnished to do so, in
** accordance with:
**
** (1) if the Software is obtained from Blackmagic Design, the End User License
** Agreement for the Software Development Kit ("EULA") available at
** https://www.blackmagicdesign.com/EULA/DeckLinkSDK; or
**
** (2) if the Software is obtained from any third party, such licensing terms
** as notified by that third party,
**
** and all subject to the following:
**
** (3) the copyright notices in the Software and this entire statement,
** including the above license grant, this restriction and the following
** disclaimer, must be included in all copies of the Software, in whole or in
** part, and all derivative works of the Software, unless such copies or
** derivative works are solely in the form of machine-executable object code
** generated by a source language processor.
**
** (4) THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
**
** A copy of the Software is available free of charge at
** https://www.blackmagicdesign.com/desktopvideo_sdk under the EULA.
**
** -LICENSE-END-
*/

#include "DeckLinkOpenGLWidget.h"
#include <QOpenGLFunctions>
#include <QDebug>
#include <QPainter>
#include <QtConcurrent/QtConcurrent>

///
/// DeckLinkOpenGLDelegate
///

DeckLinkOpenGLDelegate::DeckLinkOpenGLDelegate() : m_refCount(1)
{
}

/// IUnknown methods

HRESULT DeckLinkOpenGLDelegate::QueryInterface(REFIID iid, LPVOID *ppv)
{
    CFUUIDBytes iunknown;
    HRESULT result = S_OK;

    if (ppv == nullptr)
        return E_INVALIDARG;

    // Obtain the IUnknown interface and compare it the provided REFIID
    iunknown = CFUUIDGetUUIDBytes(IUnknownUUID);
    if (memcmp(&iid, &iunknown, sizeof(REFIID)) == 0)
    {
        *ppv = this;
        AddRef();
    }
    else if (memcmp(&iid, &IID_IDeckLinkScreenPreviewCallback, sizeof(REFIID)) == 0)
    {
        *ppv = static_cast<IDeckLinkScreenPreviewCallback *>(this);
        AddRef();
    }
    else
    {
        *ppv = nullptr;
        result = E_NOINTERFACE;
    }

    return result;
}

ULONG DeckLinkOpenGLDelegate::AddRef()
{
    return ++m_refCount;
}

ULONG DeckLinkOpenGLDelegate::Release()
{
    ULONG newRefValue = --m_refCount;
    if (newRefValue == 0)
        delete this;

    return newRefValue;
}

/// IDeckLinkScreenPreviewCallback methods

// HRESULT DeckLinkOpenGLDelegate::DrawFrame(IDeckLinkVideoFrame* frame)
// {
// 	emit frameArrived(com_ptr<IDeckLinkVideoFrame>(frame));
// 	return S_OK;
// }

HRESULT DeckLinkOpenGLDelegate::DrawFrame(IDeckLinkVideoFrame *frame)
{
    // qDebug() << "[DeckLink] Frame received:" << (frame ? "OK" : "NULL");
    emit frameArrived(com_ptr<IDeckLinkVideoFrame>(frame));
    return S_OK;
}

// HRESULT DeckLinkOpenGLDelegate::DrawFrame(IDeckLinkVideoFrame* frame)
// {
//     auto framePtr = com_ptr<IDeckLinkVideoFrame>(frame);
//     emit frameArrived(framePtr);             // For OpenGL rendering
//     emit frameForRecording(framePtr);        // For recording pipeline
//     return S_OK;
// }

///
/// DeckLinkOpenGLWidget
///

DeckLinkOpenGLWidget::DeckLinkOpenGLWidget(QWidget *parent) : QOpenGLWidget(parent)
{
    m_deckLinkScreenPreviewHelper = CreateOpenGL3ScreenPreviewHelper();
    m_delegate = make_com_ptr<DeckLinkOpenGLDelegate>();

    connect(m_delegate.get(), &DeckLinkOpenGLDelegate::frameArrived, this, &DeckLinkOpenGLWidget::setFrame, Qt::QueuedConnection);
}

void DeckLinkOpenGLWidget::clear()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    if (m_delegate)
        m_delegate->DrawFrame(nullptr);
}

/// QOpenGLWidget methods

void DeckLinkOpenGLWidget::initializeGL()
{
    // qDebug() << "initialize GL";
    if (m_deckLinkScreenPreviewHelper)
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        m_deckLinkScreenPreviewHelper->InitializeGL();
    }
}

// void DeckLinkOpenGLWidget::paintGL()
// {
// 	// qDebug() << "Paint GL";
// 	std::lock_guard<std::mutex> lock(m_mutex);
// 	m_deckLinkScreenPreviewHelper->PaintGL();
// }

// void DeckLinkOpenGLWidget::paintGL()
// {
//     std::lock_guard<std::mutex> lock(m_mutex);

//     if (!m_deckLinkScreenPreviewHelper)
//         return;

//     // Step 1: Draw raw video frame to OpenGL buffer
//     m_deckLinkScreenPreviewHelper->PaintGL();

//     // Step 2: Grab current frame
//     QImage frame = grabFramebuffer();

//     // Step 3: Apply flip based on m_flipStep
//     QImage flippedFrame;
//     switch (m_flipStep)
//     {
//         case 0:
//             flippedFrame = frame;
//             break;
//         case 1:
//             flippedFrame = frame.mirrored(true, false);  // horizontal
//             break;
//         case 2:
//             flippedFrame = frame.mirrored(true, true);   // horizontal + vertical
//             break;
//         case 3:
//             flippedFrame = frame.mirrored(false, true);  // vertical (of step 2)
//             break;
//         default:
//             flippedFrame = frame;
//             break;
//     }

//     // Step 4: Draw flipped image
//     QPainter painter(this);
//     painter.setRenderHint(QPainter::SmoothPixmapTransform);
//     painter.drawImage(0, 0, flippedFrame);

//     // Step 5: Overlay text
//     painter.setPen(Qt::white);
//     painter.setFont(QFont("Arial", 24, QFont::Bold));
//     painter.drawText(20, 40, QStringLiteral("🔴 Live • 3840×2160"));

//     painter.end();
// }

void DeckLinkOpenGLWidget::setInputSource(const QString &source)
{
    // qDebug() << "[setInputSource] this=" << this << ", source=" << source;
    m_inputSource = source;
    update();
}

void DeckLinkOpenGLWidget::paintGL()
{
    // qDebug() << "[paintGL] this=" << this << ", m_inputSource=" << m_inputSource;

    std::lock_guard<std::mutex> lock(m_mutex);

    if (!m_deckLinkScreenPreviewHelper)
        return;

    // Step 1: Draw raw video frame to OpenGL buffer
    m_deckLinkScreenPreviewHelper->PaintGL();

    // Step 2: Grab current frame
    QImage frame = grabFramebuffer();

    // Step 3: Apply flip based on m_flipStep
    QImage flippedFrame;
    switch (m_flipStep)
    {
    case 0:
        flippedFrame = frame;
        break;
    case 1:
        flippedFrame = frame.mirrored(true, false); // horizontal
        break;
    case 2:
        flippedFrame = frame.mirrored(true, true); // horizontal + vertical
        break;
    case 3:
        flippedFrame = frame.mirrored(false, true); // vertical
        break;
    default:
        flippedFrame = frame;
        break;
    }

    // Step 4: Draw flipped image
    QPainter painter(this);
    painter.setRenderHint(QPainter::SmoothPixmapTransform);
    painter.drawImage(0, 0, flippedFrame);
    
    // Step 5: Overlay text based on input source (only if enabled)
    if (m_showLabel)
    {
        painter.setPen(Qt::white);
        painter.setFont(QFont("Arial", 24, QFont::Bold));

        if (m_inputSource.compare("HDMI", Qt::CaseInsensitive) == 0)
        {
            painter.drawText(20, 40, QStringLiteral("🔴 Live • 3840×2160"));
        }
        else
        {
            // SDI or AHD
            painter.drawText(20, 40, QStringLiteral("🔴 Live • 1080@60"));
        }
    }

    painter.end();

    // ✅ Step 6: Send frame to recorder
    if (m_recording && m_videoRecorder)
    {
        if (!flippedFrame.isNull())
        {
            m_videoRecorder->recordFrame(flippedFrame);
        }
    }
}

void DeckLinkOpenGLWidget::resizeGL(int width, int height)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    QOpenGLFunctions *f = context()->functions();
    f->glViewport(0, 0, width, height);
}

/// DeckLinkOpenGLWidget slots

// void DeckLinkOpenGLWidget::setFrame(com_ptr<IDeckLinkVideoFrame> frame)
// {
// 	// qDebug() << "setFrame GL" << frame.get();
// 	if (m_deckLinkScreenPreviewHelper)
// 	{
// 		m_deckLinkScreenPreviewHelper->SetFrame(frame.get());
// 		update();
// 	}
// }

void DeckLinkOpenGLWidget::setFrame(com_ptr<IDeckLinkVideoFrame> frame)
{
    if (!frame)
    {
        qDebug() << "[DeckLinkOpenGLWidget] Received null frame!";
        return;
    }

    // qDebug() << "[DeckLinkOpenGLWidget] Received frame:" << frame.get();

    if (m_deckLinkScreenPreviewHelper)
    {
        m_deckLinkScreenPreviewHelper->SetFrame(frame.get());
        update();
    }
}

void DeckLinkOpenGLWidget::setSharedDelegate(const com_ptr<DeckLinkOpenGLDelegate> &delegate)
{
    std::lock_guard<std::mutex> lock(m_mutex);

    if (!delegate)
        return;

    // Disconnect old delegate if it existed
    if (m_delegate)
        disconnect(m_delegate.get(), nullptr, this, nullptr);

    m_delegate = delegate;

    connect(m_delegate.get(), &DeckLinkOpenGLDelegate::frameArrived, this, &DeckLinkOpenGLWidget::setFrame, Qt::QueuedConnection);
}

com_ptr<DeckLinkOpenGLDelegate> DeckLinkOpenGLWidget::delegate()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    return m_delegate;
}

void DeckLinkOpenGLWidget::setFlipStep(int step)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_flipStep = step % 5;
    update();
}

// bool DeckLinkOpenGLWidget::saveSnapshot(const QString& path)
// {
//     QImage snapshot = grabFramebuffer();  // Grabs the current OpenGL frame
//     if (snapshot.isNull())
//         return false;

//     return snapshot.save(path);  // Automatically infers format from extension
// }

bool DeckLinkOpenGLWidget::saveSnapshot(const QString &path)
{
    QImage snapshot = grabFramebuffer();

    if (snapshot.isNull())
    {
        // qDebug() << "❌ Snapshot is null.";
        return false;
    }

    // Save asynchronously
    QtConcurrent::run([snapshot, path]()
                      {
        bool success = snapshot.save(path, "JPG", 95);  // or "PNG"
        qDebug() << (success ? "✅ Snapshot saved:" : "❌ Save failed:") << path; });

    return true;
}

void DeckLinkOpenGLWidget::setShowLabel(bool show)
{
    m_showLabel = show;
    update();
}